[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "dotnet api.dll"
healthcheckPath = "/health"
healthcheckTimeout = 10
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
numReplicas = 1
ipStack = "IPV4"

[deploy.env]
DOTNET_SYSTEM_NET_DISABLEIPV6 = "1"
DOTNET_PREFER_IPV4 = "1"
DOTNET_HOST_STRICT_IP = "4"
ASPNETCORE_URLS = "http://0.0.0.0:8080"
ASPNETCORE_ENVIRONMENT = "Production"

[deploy.kv]
PORT = "8080" 